# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: cogitoexample/sshd-kubernetes
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 22
  targetPort: 22