{{- if .Values.hook.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-job
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        sidecar.istio.io/inject: "false"
        # iam.amazonaws.com/role: arn:aws:iam::{{ required "Set aws.accountId" .Values.aws.accountId }}:role/{{ required "Set aws.region" .Values.aws.region }}-v1
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: dummy
      containers:
      - name: job
        image: "{{ .Values.hook.image.repository }}:{{ .Values.hook.image.tag }}"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "source /scripts/create-user-and-database.sh" ]
        env:
        - name: AWS_DEFAULT_REGION
          value: {{ required "Set aws.region" .Values.aws.region }}
        - name: ENVIRONMENT_NAME
          value: {{ required "Set environmentName" .Values.environmentName }}
        volumeMounts:
        - name: scripts-vol
          mountPath: /scripts
      volumes:
      - name: scripts-vol
        configMap:
          name: {{ .Release.Name }}-configmap
{{- end }}