# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: naqibdocker/certd
  pullPolicy: Always
  tag: "latest"

command:
  - /bin/bash
  - -c

args:
  - mkdir ~/.ssh_ca;
    /usr/local/bin/ssh-cert-authority generate-config --url http://certd-app:8080 -k /etc/ssh-agent/requester_key.pub > ~/.ssh_ca/requester_config.json;
    export $(ssh-agent | cut -d';' -f1 | head -n 1);
    ssh-add /etc/ssh-agent/requester_key;
    /usr/local/bin/ssh-cert-authority request -e test --reason 'lol bantz thats why!' --ssh-dir /etc/ssh-agent;
    mkdir -p ~/.ssh;
    cat /etc/ssh-agent/sshd-app-host-address >> ~/.ssh/known_hosts;
    sleep infinity;

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

extraVolumeMounts:
  - name: ssh
    mountPath: "/etc/ssh-agent/requester_key"
    subPath: "requester-key"
    readOnly: true
  - name: ssh-pub
    mountPath: "/etc/ssh-agent/requester_key.pub"
    subPath: "requester-key.pub"
    readOnly: true
  - name: sshd-key
    mountPath: "/etc/ssh-agent/sshd-app-host-address"
    subPath: "sshd-pub-key"
    readOnly: true

extraVolumes:
  - name: ssh
    secret: 
      secretName: requester-key
      defaultMode: 0400
  - name: ssh-pub
    secret: 
      secretName: requester-pub-key
      defaultMode: 0400
  - name: sshd-key
    secret: 
      secretName: sshd-pub-key
      defaultMode: 0400