{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    app: {{ include "generic.fullname" . }}
    version: "{{ .Values.image.tag | default .Chart.AppVersion }}"
    {{- include "generic.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{ end }}