# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: naqibdocker/certd
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

extraVolumeMounts:
  - name: ca-ssh
    mountPath: "/etc/ssh-agent/ca_key"
    subPath: "ca-key"
    readOnly: true
  - name: ca-ssh-pub
    mountPath: "/etc/ssh-agent/ca_key.pub"
    subPath: "ca-key.pub"
    readOnly: true
  - name: config
    mountPath: "/root/.ssh_ca/sign_certd_config.json"
    subPath: "sign_certd_config.json"
    readOnly: true

extraVolumes:
  - name: ca-ssh
    secret: 
      secretName: ca-key
      defaultMode: 0600
  - name: ca-ssh-pub
    secret: 
      secretName: ca-pub-key
      defaultMode: 0600
  - name: config
    configMap:
      name: ssh-ca-certd-config