apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30022
    hostPort: 30022
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: 30023
    hostPort: 30023
    listenAddress: "0.0.0.0" 
    protocol: tcp
  - containerPort: 30024
    hostPort: 30024
    listenAddress: "0.0.0.0" 
    protocol: tcp